### ISSUE TITLE
Cannot sniff the codes

### ISSUE THREAD

**Issue by caldecy** [jderehag/rpi-rfsniffer#2]
After running the code `rfsniffer record remotename.button1` the instruction "Press remotename.Button1" appears and even after pressing my controller button, the codes are not registered! 

I have double checked my Receiver and Transceiver GPIO pin connections 27 and 17 respectively. 

Hope you can shed some light on the matter! Thanks!

**Comment by TheIndra55** [comment]
Same here

**Comment by jderehag** [comment]
Hi, sorry for the late reply.

Where did you get pin 27 & 17 from?
The default pin assignments are:
--rxpin default=13
--txpin default=11

Of course, you could change the pin assignment using (assuming rx is at 27 and tx is at 17):
`rfsniffer record --rxpin 27 --txpin 17 remotename.button1`

**Comment by TheIndra55** [comment]
My pins where on 13 & 11 but still nothing happens when i press a button on my remote, when i try rfsniffer written in C it works..

**Comment by jderehag** [comment]
That is weird.
rfsniffer simply reads bitflips using GPIO.wait_for_edge(..) and records the timing between these transitions.
GPIO basically wraps some c-library (dont know exactly which one), but I would not be surprised if its the same one you have tried.
The only filtering I do in rfsniffer is that I only record sequences longer than 5 bits (to avoid some spurious wakeups from the edge trigger).
So either something is wrong with the GPIO implementation (allthough it works fine on my RPi2), or your sequence is smaller than 5bits (which is also very unlikely if you are sniffing RF signals).

**Comment by caldecy** [comment]
Hmm, alright so I guess I'll have to try it again.

**Comment by flatsiedatsie** [comment]
Same issue here, it doesn't work. Pi Zero W.

Could you be more clear about the pins? There are so many confusing pin naming schemes. Are you talking about physical pins? GPIO? Wiring?

**Comment by jderehag** [comment]
Sorry for the late reply! I how now updated the README with clarifications on the pin layout etc. And thank you for your analysis btw.
> Recorded 472711 bit transitions
> 
> is that just noise it's recording?
Yes, very likely. It will continue recording until 1 second of silence. So that many transitions is very likely noise. But I notice you have used GPIO pin 2, which has a fixed pull-up resistor. So it might be that it interferes with the configured soft pull-down. I would try moving the rx pin and avoid pins 2-3.

> Beautiful code by the way.
Thanks!

**Comment by jderehag** [comment]
> Any pointers?

Not really, I would make sure you avoid pins 2-3, and maybe read through the updated README to see if you may spot anything that could relate to your problem. Apart from that its hard to help without any more information.

**Comment by rbirkby** [comment]
Had the same issue - not able to read anything. Then realized the rx was on 5V. Changing to a 3V3 pin and it worked.

**Comment by corlaez** [comment]
My receiver is on 5V, but I put it there because the chip says 5V+
Is that what's causing all the noise on my device as well? Should I use 3V3 even when the chip I have says 5V+?
(I altered the code to confirm that the problem is that) the inputs keep being appended over and over again, very very fast and without me trying to fire any radio signal.

**Comment by lesha369** [comment]
I fulfilled all the conditions, but the signal is still not read.
writes `press button` and nothing happens when the signal is given.
but the rf433utils library works but does not work with the remote that I need.
Previously, this all worked, but it does not work on a clean raspberry os 64arm. help me please

- changed receiver from 5v to 3v
- used different pins (except unwanted ones)
- tried python2, python3
